### ISSUE TITLE
Setup in IIS?

### ISSUE THREAD

**Issue by fletch8527** [grantemsley/snipe-hacks-public#1]
I'm looking to get a Dymo 450 to print asset tags via Snipe. I have Snipe hosted on WS2016 with IIS. Any idea how I would get your dymo label printing script to work on WS2016 w/ IIS?

**Comment by grantemsley** [comment]
Sorry no, I have never tried it on IIS.

**Comment by fletch8527** [comment]
Ok, I'm going to see if I can get it to work on IIS. Would you happen to know where the config.php file is supposed to go? does it go in the 'web' folder or one level higher?
